### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by purefan** [ebemunk/node-uci#14]
Loving the project! it works really well for my needs! Today I wanted to add an event emitter to the info message from the engine so the first thing I did was `git clone` and right after `npm instal` + `npm test` but all the tests failed.

I dont want to add features if the base tests are failing, makes me think I wont be able to reliably test what I develop. 

Did I miss a step or config?

**Comment by purefan** [comment]
if it helps I run node 8.10

**Comment by ebemunk** [comment]
hi @purefan thanks for your interest.

can you give some more info on the test failures? as you can see the master tests are passing on the CI, https://travis-ci.org/ebemunk/node-uci/builds/432783610 . i also tried it on my machine, albeit using node 12.5.0 and yarn 1.16.0 and got no failures. i have not tried it with node 8.10 but i imagine it should not be failing.

if you provide a log of the test failures i can try to see why that might be.

**Comment by purefan** [comment]
I get a bunch of errors like this https://gist.github.com/purefan/6dfdb478c51908ef6aefc1a1dd5349be it looks to me like babel just isnt working but it may also be something about the node version that I run

**Comment by ebemunk** [comment]
just tried it with node -v v8.16.0 and npm 6.4.1 and had no issues. are you sure you still have the `.babelrc` in the repo folder?

**Comment by purefan** [comment]
Yeap, `.babelrc` is in the root folder in the repo
![image](https://user-images.githubusercontent.com/315880/62243870-7810f680-b3de-11e9-9600-d7ad1f061288.png)

**Comment by purefan** [comment]
This is interesting because if I run `$(npm bin)/jest --showConfig` I see the transform includes babel: 
```
"transform": [
        [
          "^.+\\.jsx?$",
          "/path/to/node-uci/node_modules/jest-config/node_modules/babel-jest/build/index.js"
        ]
      ],
```

**Comment by purefan** [comment]
For what is worth, I updated all the dependencies to the latest versions (with `npm-check-updates`) and `npm test` still fails every test

**Comment by purefan** [comment]
I gave it another try today with node 10.17 and still got all tests failing:
```

 FAIL  src/Engine/__test__/sendCmd.test.js
  ● Test suite failed to run

    Babel 7.0.0-beta.56 has dropped support for the 'helpersNamespace' utility.If you are using @babel/plugin-external-helpers you will need to use a newer version than the one you currently have installed. If you have your own implementation, you'll want to explore using 'helperGenerator' alongside 'file.availableHelper()'.

      at File.set (node_modules/@babel/core/lib/transformation/file/file.js:125:13)
      at PluginPass.pre (node_modules/babel-plugin-external-helpers/lib/index.js:10:12)
      at transformFile (node_modules/@babel/core/lib/transformation/index.js:78:27)
      at runSync (node_modules/@babel/core/lib/transformation/index.js:45:3)
      at transformSync (node_modules/@babel/core/lib/transform.js:43:38)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:387:35)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:457:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)

```

The reason why I want to tweak the project is because lodash has a security vulnerability, my project got a warning from github's security checks and want to fix that asap

**Comment by ebemunk** [comment]
hi @purefan i have upgraded all the dependencies for node-uci, and now have Travis running for node 10, 12 and 13.
thanks for bringing up the security issue, the new upgrades should fix them.
you can see the tests pass for all 3 envs over here: https://travis-ci.org/ebemunk/node-uci/builds/634076853
hopefully this will fix your problems

**Comment by purefan** [comment]
Thanks a lot @ebemunk ! Indeed I can now run all the tests and the security warning should be gone :) I very much appreciate your attention to this issue and hope you have a wonderful day
