### ISSUE TITLE
Camel Case

### ISSUE THREAD

**Issue by weslenng** [ebemunk/node-uci#25]

**Comment by weslenng** [comment]
I'm open to do a PR to fix this issue, but I don't know if `bestmove` in lower case is on purpose

**Comment by ebemunk** [comment]
Thanks for opening this issue.

`node-uci` is a wrapper around the UCI protocol, and it's named as `bestmove` in there (see: https://github.com/ebemunk/node-uci/blob/master/uci.txt#L203)

Making it `bestMove` would be an arbitrary decision and I wouldn't want to do that, especially that the actual communication from the engine (the message that the engine sends) is `bestmove`.

Considering above, I think I'm going to keep it as `bestmove`.

Thanks!
