### ISSUE TITLE
go mate does not seem to work

### ISSUE THREAD

**Issue by edelah** [ebemunk/node-uci#27]
When I run this code, the engine results show that it did not stop after finding a mate. Whereas using the same engine with its command prompt show that it output only the best line for a mate.

code to reproduce
=============
import { Engine } from "node-uci";
import { performance } from "perf_hooks";

(async () => {
  const engine = new Engine(
    "/home/unknown/stockfish_13_linux_x64_avx2/stockfish_13_linux_x64_avx2/stockfish_13_linux_x64_avx2"
  );
  const start = performance.now();

  engine
    .chain()
    .init()
    .setoption("MultiPV", "3")
    .position("r1b2rk1/5ppp/p1pp4/P3q3/3p4/P7/5PPP/RN4K1 b - - 0 20")
    .go({ depth: 8, mate: 8 })
    .then((result) => {
      console.log(
        `Elapsed time:, ${(performance.now() - start) / 1000} seconds`
      );
      console.log(" result:", JSON.stringify(result));
    })
    .catch((err) => console.log("err:", err));
})();

output
==================
Elapsed time:, 0.3082094999998808 seconds
 result: {"bestmove":"e5e1","info":[{"string":"NNUE evaluation using nn-62ef826d1a6d.nnue enabled"},{"depth":1,"seldepth":2,"time":1,"nodes":112,"nps":112000,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":1,"seldepth":1,"time":1,"nodes":112,"nps":112000,"tbhits":0,"score":{"unit":"cp","value":1686},"multipv":2,"pv":"e5a5"},{"depth":1,"seldepth":1,"time":1,"nodes":112,"nps":112000,"tbhits":0,"score":{"unit":"cp","value":1655},"multipv":3,"pv":"c6c5"},{"depth":2,"seldepth":2,"time":2,"nodes":300,"nps":150000,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":2,"seldepth":2,"time":2,"nodes":300,"nps":150000,"tbhits":0,"score":{"unit":"cp","value":2001},"multipv":2,"pv":"d4d3 g2g3"},{"depth":2,"seldepth":2,"time":2,"nodes":300,"nps":150000,"tbhits":0,"score":{"unit":"cp","value":1778},"multipv":3,"pv":"c8f5 g2g3"},{"depth":3,"seldepth":2,"time":2,"nodes":561,"nps":280500,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":3,"seldepth":3,"time":2,"nodes":561,"nps":280500,"tbhits":0,"score":{"unit":"cp","value":2001},"multipv":2,"pv":"d4d3 g2g3 e5a1"},{"depth":3,"seldepth":4,"time":2,"nodes":561,"nps":280500,"tbhits":0,"score":{"unit":"cp","value":1778},"multipv":3,"pv":"c8f5 g2g3 e5e1 g1g2 f5b1"},{"depth":4,"seldepth":2,"time":2,"nodes":716,"nps":358000,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":4,"seldepth":5,"time":2,"nodes":716,"nps":358000,"tbhits":0,"score":{"unit":"cp","value":2017},"multipv":2,"pv":"c8f5 g2g3"},{"depth":4,"seldepth":4,"time":2,"nodes":716,"nps":358000,"tbhits":0,"score":{"unit":"cp","value":2015},"multipv":3,"pv":"d4d3 g2g3 e5a1"},{"depth":5,"seldepth":2,"time":3,"nodes":1571,"nps":523666,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":5,"seldepth":5,"time":3,"nodes":1571,"nps":523666,"tbhits":0,"score":{"unit":"cp","value":2109},"multipv":2,"pv":"d4d3 g2g3 e5a1"},{"depth":5,"seldepth":6,"time":3,"nodes":1571,"nps":523666,"tbhits":0,"score":{"unit":"cp","value":2032},"multipv":3,"pv":"e5a5 g2g3 a5e1 g1g2"},{"depth":6,"seldepth":2,"time":3,"nodes":2379,"nps":793000,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":6,"seldepth":7,"time":3,"nodes":2379,"nps":793000,"tbhits":0,"score":{"unit":"cp","value":2101},"multipv":2,"pv":"d4d3 h2h3 e5a1 f2f3 a1b1 g1f2 d3d2"},{"depth":6,"seldepth":8,"time":3,"nodes":2379,"nps":793000,"tbhits":0,"score":{"unit":"cp","value":2048},"multipv":3,"pv":"a8b8 g2g3 d4d3 g1g2 e5a1"},{"depth":7,"seldepth":2,"time":4,"nodes":3177,"nps":794250,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":7,"seldepth":8,"time":4,"nodes":3177,"nps":794250,"tbhits":0,"score":{"unit":"cp","value":2114},"multipv":2,"pv":"d4d3 h2h3 e5a1 f2f3 a1b1 g1f2 d3d2"},{"depth":7,"seldepth":8,"time":4,"nodes":3177,"nps":794250,"tbhits":0,"score":{"unit":"cp","value":1916},"multipv":3,"pv":"a8b8 g2g3 d4d3 a1a2 b8b1 g1g2 e5e1 g3g4 e1g1 g2f3 g1g4 f3e3"},{"depth":8,"seldepth":2,"time":8,"nodes":11017,"nps":1377125,"tbhits":0,"score":{"unit":"mate","value":1},"multipv":1,"pv":"e5e1"},{"depth":8,"seldepth":10,"time":8,"nodes":11017,"nps":1377125,"tbhits":0,"score":{"unit":"cp","value":2114},"multipv":2,"pv":"d4d3 h2h3 e5a1 g1h2 a1b1 h2g3 d3d2"},{"depth":8,"seldepth":11,"time":8,"nodes":11017,"nps":1377125,"tbhits":0,"score":{"unit":"cp","value":1794},"multipv":3,"pv":"e5a5 g2g4 c8g4 g1g2 g7g6 g2g3 f7f5"}]}

output of stockfish prompt
====================
![error mate](https://user-images.githubusercontent.com/17884712/113448129-886f4500-93fb-11eb-9725-f38973c7eb44.PNG)

**Comment by ebemunk** [comment]
Hi, thanks for opening this issue.

I'm not sure what you're asking here. As you can see from your own results, the engine does find the best move and `node-uci` reports it correctly: in your own output you can see `result: {"bestmove":"e5e1","info":[{...`

I tested your code myself as well, and it works as intended. If you `console.log(result.bestmove)` you will see the output `e5e1`.

I think you are asking why the node process doesn't quit after finding the bestmove and going through your promise chain. This is because you never call `engine.quit()` after `engine.go` so the engine process is still open (but it is idle - it's not doing work, but the pipe is still alive). You need to call `engine.quit()` at some point so that node will know you're done with the resource and exit the process.

This is called "resource management". You can read [this answer in stackoverflow](https://stackoverflow.com/a/7699579) to a related issue or research how to clean up resources after you're done and no longer need them.

In this case, as long as you call `engine.quit()` node will terminate the process after your promise chain.

Hope that was helpful, and thanks for using `node-uci`.

**Comment by edelah** [comment]
Thanks. You are right, I misundersood the functioning of the library.
