### ISSUE TITLE
Stockfish 8 UCI for Windows implementaion into node.uci

### ISSUE THREAD

**Issue by yellow-panther** [ebemunk/node-uci#7]
Hello, could you please explain me (step by step) how to run and embed an UCI-compatible chess engine e.g. SF 8 https://stockfishchess.org/ into https://github.com/ebemunk/node-uci ?

I have installed Node.js (including node.npm) for Windows https://nodejs.org/en/  and MS VS 2017 Communityhttps://www.visualstudio.com/de/downloads/?rr=https%3A%2F%2Fwww.google.de%2F

**Comment by ebemunk** [comment]
Hi, have you tried the example code on the readme? the only thing you need to know is the path to the executable (location where you downloaded stockfish).

**Comment by yellow-panther** [comment]
Well I have successfully embedded UCI engines for Windows (executables)  32/64 bit into more than two dozens GUIs (mostly interactive, shareware respectively freeware ) cf. http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list , but package .json is really a mystery for me. Do you know an application for Windows  to open files with the format  http://www.json.org/ ? I would add this step-by-step manual on ComputerChess Wikipedia too.
Which other software except MS Visual Studio 2017 and Node.Js is required to run your node.uci program?

**Comment by ebemunk** [comment]
This is not a GUI or a program you can "open" to use an engine, this provides a library for communicating with UCI engines with the uci protocol. The programs you sent on that list all communicate through this protocol (this would be opaque to you as a user, the GUI handles it in the implementation). This project on the other hand is neither a GUI or an executable, it is a library to be used in other software programs (namely, javascript via node.js). In a sense, a GUI you can execute might use this project to communicate with the engine from behind the scenes.

It seems to me you're looking to use an engine with a GUI, so this project is not a good candidate to do that. If you had some software (for example and automatic game analyzer) that needed to speak to an engine at some point, that would be the use case. This is just the library, so you can't execute anything without actually writing the code to do so.
