### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Scorpibear** [ebemunk/node-uci#8]
Find this issue when using stockfish9
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at Pipe.onread (net.js:615:25)

**Comment by ebemunk** [comment]
thanks for reporting this, can you provide some more details as to when this happens? the logs would be most helpful, which you can obtain by running `DEBUG=uci:Engine:log myscript.js > log.txt` i.e. by providing the `DEBUG=uci:Engine:log` environment var to your script.

in the meantime i will try to reproduce this on some free time

**Comment by ebemunk** [comment]
hey @Scorpibear i could not reproduce this with the latest version of stockfish 9 from the website. the "real" tests run just fine without the ECONNRESET. are you sure you are supplying the correct path for the executable?

**Comment by ebemunk** [comment]
published a new patch, could not reproduce this. feel free to open if you run into this issue with 1.3.1
